// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/dyegopenha/jwt-playground/internal/app/server/handler"
	"github.com/dyegopenha/jwt-playground/internal/app/server/middleware"
	"github.com/dyegopenha/jwt-playground/internal/app/server/router"
	"github.com/dyegopenha/jwt-playground/internal/config/env"
	"github.com/dyegopenha/jwt-playground/internal/domain/usecase"
	"github.com/dyegopenha/jwt-playground/internal/pkg/jwtutil"
	"github.com/dyegopenha/jwt-playground/internal/pkg/validator"
	"github.com/dyegopenha/jwt-playground/internal/provider/cache/redis"
)

// Injectors from wire.go:

func New() *Server {
	validation := validator.New()
	envEnv := env.NewEnv(validation)
	jwtUtil := jwtutil.NewJWTUtil(envEnv)
	middlewareMiddleware := middleware.NewMiddleware(jwtUtil)
	redisRedis := redis.NewRedis(envEnv)
	signInUseCase := usecase.NewSignInUseCase(envEnv, redisRedis, jwtUtil)
	refreshUseCase := usecase.NewRefreshUseCase(redisRedis, envEnv, jwtUtil)
	authHandler := handler.NewAuthHandler(envEnv, signInUseCase, refreshUseCase)
	userHandler := handler.NewUserHandler()
	routerRouter := router.NewRouter(middlewareMiddleware, authHandler, userHandler)
	server := newServer(envEnv, routerRouter)
	return server
}
